image: docker:20.10.5
services:
  - docker:20.10.5-dind
stages:
  - build
  - test

variables:
  CI_IMAGE_FULLPATH: $CI_REGISTRY/$CI_PROJECT_PATH/python-api

docker-build:

  stage: build

  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - export CI_IMAGE_FULLPATH_LOWERCASE=$(eval 'echo "$CI_IMAGE_FULLPATH" | tr "[:upper:]" "[:lower:]"')
    - echo "Image path is '$CI_IMAGE_FULLPATH_LOWERCASE'"
  # Default branch leaves tag empty (= latest tag)
  # All other branches are tagged with the escaped branch name (commit ref slug)
  script:
    - |
      if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
        tag=""
        echo "Running on default branch '$CI_DEFAULT_BRANCH': tag = 'latest'"
        docker build --pull -t "$CI_IMAGE_FULLPATH_LOWERCASE${tag}" .
        docker push "$CI_IMAGE_FULLPATH_LOWERCASE${tag}"
      else
        tag=":$CI_COMMIT_REF_SLUG"
        echo "Running on branch '$CI_COMMIT_BRANCH': tag = $tag"
        docker build --pull -t "$CI_IMAGE_FULLPATH_LOWERCASE${tag}" .
      fi

docker-test:
  stage: test
  script:
    - |
      if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
        tag=""
      else
        tag=":$CI_COMMIT_REF_SLUG"
      fi
      export CI_IMAGE_FULLPATH_LOWERCASE=$(eval 'echo "$CI_IMAGE_FULLPATH" | tr "[:upper:]" "[:lower:]"')
      docker run -d -p 5290:5290 --name server "$CI_IMAGE_FULLPATH_LOWERCASE${tag}"
      sleep 15
      if ( curl -s http://localhost:5290/get_info | grep 'Running' ); then
        echo "WORK"
        docker stop server
        docker rm server
        docker image remove "$CI_IMAGE_FULLPATH_LOWERCASE${tag}"
      else
        echo "DONT WORK"
        docker stop server
      fi
